### ISSUE TITLE
Regression in v4.0.6 handling `after` callbacks

### ISSUE THREAD

**Issue by peterkeen** [aasm/aasm#197]
I believe 4.0.6 introduces a regression, specifically in this commit:

https://github.com/aasm/aasm/commit/bb01034c1a5cdfb9be8043648f17b116e1cebdd0

In 4.0.5 Payola's [state](https://github.com/peterkeen/payola/blob/master/app/models/payola/sale.rb#L22-L44) [machines](https://github.com/peterkeen/payola/blob/master/app/models/payola/subscription.rb#L25-L51) pass tests and work great, but with 4.0.6 the tests fail with the following errors (a whole slew of them, this is just a representative sample):

```
  1) Payola::ChargeCard#call should not create a customer if one already exists
     Failure/Error: ChargeCard.call(sale)
     NoMethodError:
       NoMethodError: undefined method `instrument_finish' for #<AASM::Core::Event:0x007fe860514258 @name=:finish, @transitions=[#<AASM::Core::Transition:0x007fe860514960 @from=:processing, @to=:finished, @guards=[], @unless=[], @after=[], @opts={:from=>:processing, :to=>:finished}>], @guards=[], @unless=[], @options={:after=>:instrument_finish}>:AASM::Core::Event
     # ./app/services/payola/charge_card.rb:15:in `call'
     # ./spec/services/payola/charge_card_spec.rb:17:in `block (3 levels) in <module:Payola>'
```
