### ISSUE TITLE
rails 3.1 + aasm causes a WARNING :(

### ISSUE THREAD

**Issue by jugyo** [aasm/aasm#38]
```
[DEPRECATION WARNING] Nested I18n namespace lookup under "activerecord.attributes.XXXX" is no longer supported
```

I avoid this like: https://gist.github.com/1291907

**Comment by TangMonk** [comment]
nest is better +1, but 4.5.1 is still

**Comment by alto** [comment]
@TangMonk What do you mean?

**Comment by TangMonk** [comment]
@alto , please look at following translation:

```
 activerecord:
    attributes:
      purchase:
        state/complete: "eingelöst"
        state/awaiting_account_transaction: "wartet auf Transaktion"
        state/cancelled: "storniert"
        state/charge_failed: "belasten ist fehlgeschlagen"
        state/charged: "aufgeladen"
```

It will works, But the nest syntax is weird, the better is nested: 

```
 activerecord:
    attributes:
      purchase:
        state:
          complete: "eingelöst"
          awaiting_account_transaction: "wartet auf Transaktion"
          cancelled: "storniert"
          charge_failed: "belasten ist fehlgeschlagen"
          charged: "aufgeladen"
```
